micronaut:
  application:
    name: backend
  server:
    port: 8082
    cors:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  refresh:
    enabled: true
    sensitive: false
